---
title: Create Tournament
---
sequenceDiagram
    actor admin as Administrator

    participant tournament as Tournament
    participant database as Database
    participant sport as Sport

    admin ->> tournament: new Tournament(name, type, based)
    activate tournament
    activate admin
    Note left of admin: other parameter are default
    Note left of admin: for creating new tournament

    alt is team based
        admin ->> tournament: set number of students in each team
        admin ->> tournament: set number of teams
    else is individual based
        admin ->> tournament: set number of students
    end

    admin ->> tournament: set tournament period
    admin ->> tournament: set period between rounds

    tournament ->> database: get sports
    activate database
    database ->> sport: new Sport
    activate sport
    Note right of sport: return ArrayList<Sport>
    sport -->> admin: return sports
    deactivate sport

    admin ->> tournament: set sport/game
    deactivate admin

    tournament ->> database: add to database
    deactivate tournament
    deactivate database
