---
title: Register in Tournament
---
sequenceDiagram
    actor student_actor as Student

    participant tournament as Tournament
    participant team as Team
    participant student_class as Student
    participant database as Database
    participant email as Email

    student_actor ->> tournament: select tournament open for registration
    activate tournament
    activate student_actor
    alt is team based
        student_actor ->> team: new Team
        activate team
        team ->> tournament: add participant
        deactivate team

        tournament ->> database: validate all student_actor aren't participating in same tournament
        activate database
        database -->> tournament: OK
    else is individual based
        student_actor ->>  student_class: new Student
        activate student_class
        deactivate student_actor
        student_class ->> tournament: add participant
        deactivate student_class
    end

    tournament ->> database: add to database
    deactivate database

    tournament ->> email: send confirmation email
    activate email
    deactivate email

    deactivate tournament
