@startuml project
left to right direction

actor Administrator as admin
actor Participant as particip

rectangle "Tournaments Arranger" {
    usecase "Create tournament" as create_tournaments

    usecase "Edit tournament" as edit_tournament_data
    usecase "Edit match scores" as edit_match_scores
    edit_match_scores -up-> edit_tournament_data #line.dashed : <<extends>>
    usecase "Record match scores" as record_match_scores
    record_match_scores -up-> edit_tournament_data #line.dashed : <<extends>>
    usecase "Stop registration" as stop_registration
    stop_registration -up-> edit_tournament_data #line.dashed : <<extends>>
    usecase "Archive tournament" as archive_tournament
    archive_tournament -up-> edit_tournament_data #line.dashed : <<extends>>

    usecase "View match scores" as view_match_scores
    usecase "View participant rankings" as view_participant_ranking
    usecase "View matches schedule" as view_match_schedule
    usecase "Add sport/game" as add_sport_game

    usecase "View participant profile" as view_participant_profile
    usecase "Create team" as create_team
    usecase "Generate matches" as generate_matches
    usecase "Leave tournament" as leave_tournament
    usecase "Register in tournament" as register_in_tournament
}

admin --> create_tournaments
admin --> edit_tournament_data
admin --> generate_matches
admin --> add_sport_game

admin ---> view_match_schedule
particip --> view_match_schedule
admin --> view_participant_ranking
particip --> view_participant_ranking
admin --> create_team
particip --> create_team
admin --> view_participant_profile
particip --> view_participant_profile
admin --> view_match_scores
particip --> view_match_scores

particip --> register_in_tournament
particip --> leave_tournament
@enduml
